<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'blobfolio\\wp\\duplicity\\attachment' => '/blobfolio/wp/duplicity/attachment.php',
                'blobfolio\\wp\\duplicity\\cli' => '/blobfolio/wp/duplicity/cli.php',
                'blobfolio\\wp\\duplicity\\plugin' => '/blobfolio/wp/duplicity/plugin.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\bc' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/bc.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\cast' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/cast.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\constants' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/constants.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\data' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/data.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\dom' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/dom.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\file' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/file.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\format' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/format.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\mb' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/mb.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\cast' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\cast_base' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast_base.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\cast_full' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast_full.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\file' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/file.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\format' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/format.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\mb' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/mb.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\ref\\sanitize' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/sanitize.php',
                'blobfolio\\wp\\duplicity\\vendor\\common\\sanitize' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/sanitize.php',
                'blobfolio\\wp\\duplicity\\vendor\\domain\\data' => '/vendor/blobfolio/blob-domain/lib/blobfolio/domain/data.php',
                'blobfolio\\wp\\duplicity\\vendor\\domain\\domain' => '/vendor/blobfolio/blob-domain/lib/blobfolio/domain/domain.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
